### ISSUE TITLE
Question about TED-M

### ISSUE THREAD

**Issue by munchmoo** [hailanyi/TED#12]
Hello, Thank you for sharing your work.

As the paper mentions TED-M version uses both RGB and Lidar point clouds.  I wonder where these two modal get fused.

I can see that the two modals produce separate voxel features from TeSparseConv and get concatenated in ROI process. 

However, do you perform TeBEV pool and TeVoxel pool only for Lidar point clouds? 
--> if my understanding is right, why not perform on RGB pseudo points? 

Thank you.

**Comment by hailanyi** [comment]
I only performed TeBEV pooling for LiDAR points. The other operators are performed on both LiDAR and RGB points.
From my past experiments, using the RGB features in the TeBEV pooling cannot bring performance gain. I guess the LiDAR features in the RPN are enough to produce high recall object proposals.  Considering that the TeBEV pooling is designed for speeding up the RPN while using the RGB features brings unnecessary computation, I did not use such features.
