### ISSUE TITLE
how to add 'pedestrian' and 'cyclist' in to results?

### ISSUE THREAD

**Issue by Dowe-dong** [hailanyi/TED#14]
Thank u for your contribution Fristly. However, I found there are only one kind named 'car' in the valuation result.  I also want to try its performance about 'pedestrian' and 'cyclist'.  Could you please tell me how to add it? Thank you very much in advance. all of evaluation data about them is equal to 0.

**Comment by Dowe-dong** [comment]
AT the same time, I am aslo confused to your model. Is it realy work for 'pedestrian' and 'cyclist' ?

**Comment by hailanyi** [comment]
Currently, the released model only trained for car cls, so the metrics are zeros. Please train 3-cls model by yourself using the similar config of [CasA-V](https://github.com/hailanyi/CasA/blob/master/tools/cfgs/kitti_models/CasA-V.yaml). Note that, the hyper parameters of 2D backbone, dense head, training epoch and score threshold should be further tuned to attain a good performance. In addition, the 3-cls model is scheduled to be released in my next project，TED project will do not update again.

**Comment by Dowe-dong** [comment]
> Currently, the released model only trained for car cls, so the metrics are zeros. Please train 3-cls model by yourself using the similar config of [CasA-V](https://github.com/hailanyi/CasA/blob/master/tools/cfgs/kitti_models/CasA-V.yaml). Note that, the hyper parameters of 2D backbone, dense head, training epoch and score threshold should be further tuned to attain a good performance. In addition, the 3-cls model is scheduled to be released in my next project，TED project will do not update again.
thank you a lot.
