### ISSUE TITLE
When add 'pedestrian' and 'cyclist'  metrics are zero

### ISSUE THREAD

**Issue by Zeysthingz** [hailanyi/TED#15]
When I add pedestrian and cyclist classes for TED-S metric results are become zero and it gives good result for only car so does TED-S trained with only car class ?

Thank yo so much.

**Comment by hailanyi** [comment]
Currently, the released model only trained for car cls, so the metrics are zeros. Please train 3-cls model by yourself using the similar config of [CasA-V](https://github.com/hailanyi/CasA/blob/master/tools/cfgs/kitti_models/CasA-V.yaml). Note that, the hyper parameters of 2D backbone, dense head, training epoch and score threshold should be further tuned to attain a good performance. In addition, the 3-cls model is scheduled to be released in my next project，TED project will do not update again.

**Comment by Zeysthingz** [comment]
> Currently, the released model only trained for car cls, so the metrics are zeros. Please train 3-cls model by yourself using the similar config of [CasA-V](https://github.com/hailanyi/CasA/blob/master/tools/cfgs/kitti_models/CasA-V.yaml). Note that, the hyper parameters of 2D backbone, dense head, training epoch and score threshold should be further tuned to attain a good performance. In addition, the 3-cls model is scheduled to be released in my next project，TED project will do not update again.

Thank you so much
