### ISSUE TITLE
How can i train a multi-class network？

### ISSUE THREAD

**Issue by superlcw** [hailanyi/TED#17]
I train a multi-class(3 classes) model on kitti-datasets according to your configuration, but the result is far from the paper. How can i fixed it?

**Comment by hailanyi** [comment]
Please refer to [this issue](https://github.com/hailanyi/TED/issues/15).

**Comment by yuezhao1** [comment]
> I train a multi-class(3 classes) model on kitti-datasets according to your configuration, but the result is far from the paper. How can i fixed it?

Hello, I would like to ask, the results you mentioned are far from the paper. This means that there are values for all three categories, but lower values for pedestrians and cyclists. Or do both Pedestrian and Cyclist have values of 0?
I tried to modify the yaml file to build a multi-category network, but only Car has a value, and the evaluation results of the other two categories are always 0.
Looking forward for your reply, thank you

**Comment by yuezhao1** [comment]
> I train a multi-class(3 classes) model on kitti-datasets according to your configuration, but the result is far from the paper. How can i fixed it?

@superlcw Hello, I would like to ask, the results you mentioned are far from the paper. This means that there are values for all three categories, but lower values for pedestrians and cyclists. Or do both Pedestrian and Cyclist have values of 0?
I tried to modify the yaml file to build a multi-category network, but only Car has a value, and the evaluation results of the other two categories are always 0.
Looking forward for your reply, thank you

**Comment by yuezhao1** [comment]
@superlcw Have you reproduced the accuracy of the three types of objects in the author's paper now? The three categories I trained are all lower than those in the author's paper, cars are more than 1 point lower, pedestrians are about 7 points lower, and cyclists are 5 points lower. But I can reproduce the accuracy of a single category car based on the configuration file provided by the author.
