### ISSUE TITLE
ted_head中“def obtain_conf_preds( )”的作用是什么？

### ISSUE THREAD

**Issue by Gmonster-24** [hailanyi/TED#19]
感谢您出色的工作！RT！

**Comment by hailanyi** [comment]
这是从我之前[CasA](https://github.com/hailanyi/CasA)工作里继承来的，可以看下论文，里面有描述。其过程是将RoI分成不同部分，然后RPN分别预测不同部分的置信度，并将不同部分的置信度平均作为整体RoI的置信度预测。
