### ISSUE TITLE
TED-M 无法复现

### ISSUE THREAD

**Issue by ywh939** [hailanyi/TED#20]
你好！

我在复现你代码的过程中，发现只有TED-S可以复现，而TED-M在你配置文件默认设置的30个epoch以内，Car3D（R40)，Mod/Hard 只有87/82，又跑了一遍后，Hard甚至只有不到78！

**Comment by hailanyi** [comment]
你能提供更多细节吗？我在发布代码之前让很多人做过测试，都是可以复现的。
我想你不能复现，大概率是哪个地方的设置或者数据有问题。
但如果你只是评述一下，不提供任何细节，我帮不了你（或者你自己也没想要解决，只是简单测试下？？？）

**Comment by ywh939** [comment]
感谢回复！

我复现过SFD，所以依然在docker部署的，环境如下：
<img width="498" alt="微信截图_20230412105928" src="https://user-images.githubusercontent.com/27114849/231337065-ffcadc43-25b4-43c5-90c0-1892264f4ca4.png">

TED-S 使用命令 python train.py --cfg_file cfgs/models/kitti/TED-S.yaml 复现结果：

<img width="428" alt="微信截图_20230408103345" src="https://user-images.githubusercontent.com/27114849/231337205-12cb8385-01a7-4f08-9532-3abb6888b476.png">

TED-M 使用命令 python train.py --cfg_file cfgs/models/kitti/TED-M.yaml 复现结果：

<img width="397" alt="微信截图_20230409100041" src="https://user-images.githubusercontent.com/27114849/231337247-01c94640-d44d-4a21-b253-5237c36d7b81.png">

我准备多增加10个epoch看看，现在正在跑：
<img width="889" alt="微信截图_20230412110226" src="https://user-images.githubusercontent.com/27114849/231337405-3d767bf2-f0df-4c2b-be94-9998dad48f62.png">

我以为国内的不会回复，所以只是简单提了一下，抱歉。

**Comment by hailanyi** [comment]
你能把训练的log贴出来吗？仅仅这样，我还是没办法判断问题出在哪里。另外训练TED-M需要额外的数据，你是如何处理的？
代码有任何修改吗？你有测试过我开放的TED-M模型吗，这个精度是否正确？

**Comment by ywh939** [comment]
1. 等这40个跑完，我给你发log，但txt文件我怎么发给你呢？

2. 数据集一部分从kitti下载的，一部分从你的百度云下载的。

3. 代码没修改。

4. 还没有测你训练好的，等跑完目前的再看看。

<img width="848" alt="微信截图_20230412112422" src="https://user-images.githubusercontent.com/27114849/231341529-8b30ede3-0654-4536-82f8-ffd6e235e64d.png">

**Comment by hailanyi** [comment]
txt传到网盘，贴个链接就行。如果代码和数据不存在问题，那大概率是环境问题了。我之前没测试过单卡训练，可能是这方面原因。你先跑完吧，然后测试下我开放的模型，确保数据没问题。然后我再看看log，看看哪些参数需要调整

**Comment by ywh939** [comment]
我把log传上去了，后缀名my的是我跑了40遍的结果，后缀名your是你训练好的，eval结果。
按你所说可能数据的问题？我过段时间再看看，可能会从头再复现一遍吧。


链接：https://pan.baidu.com/s/1B7hDmi4hXUZgh-zEazNgpg?pwd=2bxg 
提取码：2bxg 
![991826E763729DEE720E97E391B57E0E](https://user-images.githubusercontent.com/27114849/231688731-ca57dc07-8a72-4b7d-aea8-472729c18674.png)

**Comment by hailanyi** [comment]
我看了，可能是单卡训练导致目标recall上不去，AP计算出现了严重下滑。
你可以不用重新训练，调整一下后处理的score threshold，再测试，保留更多的预测结果，精度应该就能上去了。
默认的是0.7，试一下0.6, 0.5, 0.4, 0.3 等阈值吧。

```
    POST_PROCESSING:
        RECALL_THRESH_LIST: [0.3, 0.5, 0.7]
        SCORE_THRESH: 0.7  # 将这个阈值分别设置成 0.6, 0.5, 0.4, 0.3 试一下 
        OUTPUT_RAW_SCORE: False
        EVAL_METRIC: kitti
```

**Comment by ywh939** [comment]
非常感谢！

后续我在试试。

**Comment by hailanyi** [comment]
问题解决了吗？不需要重新训练，验证应该很快的。

**Comment by ywh939** [comment]
刚试了0.6和0.5，mod提升明显，hard变化很小。

以后我自己再研究吧，不打扰啦。非常感谢及时回复！

**Comment by Feidashen1** [comment]
请问你解决了吗，我在复现的时候和你遇到了同样的问题

**Comment by ywh939** [comment]
没有

**Comment by chenyu31** [comment]
因为KITTI数据集的Hard会不稳定，我也是单卡训练，如果Mod验证后可以保证paper中的精度，其实差别不大。

**Comment by PanGao-1** [comment]
> 因为KITTI数据集的Hard会不稳定，我也是单卡训练，如果Mod验证后可以保证paper中的精度，其实差别不大。

请问作者说的多卡训练的Recall比单卡训练的高是对的么？因为提交KITTI test确实需要recall高的模型，如果是这样的话，单卡训练就寄了
