### ISSUE TITLE
模型第一阶段指标不好

### ISSUE THREAD

**Issue by 760440356** [hailanyi/TED#21]
我使用由您提供的模型运行test.py,发现不论是TED-S还是TED-M都是第一阶段的召回和精度很低（甚至接近于0），然而第二阶段召回和精度很高这是正常的吗

**Comment by hailanyi** [comment]
应该是roi和ground truth没在同一个坐标系下，请确保两者在同一个坐标系下

**Comment by QYChan** [comment]
作者你好，我用TED的create_kitti_info重新生成了训练需要的数据，但第一阶段的ROI仍然很低，这是为什么呢？

**Comment by yanglanq** [comment]
kitti 的 test 数据集没有label标签，因此计算的结果都是 0
