### ISSUE TITLE
Why should the training and testing logic in BackBone3D be different?

### ISSUE THREAD

**Issue by minju-Kang** [hailanyi/TED#23]
Thank you for sharing your work!

In class TeVoxelBackBone8x, you used different fuction for training and testing. 
https://github.com/hailanyi/TED/blob/8c455aca982149f5630f48d2bc6db21b26e63dfe/pcdet/models/backbones_3d/spconv_backbone.py#L736
https://github.com/hailanyi/TED/blob/8c455aca982149f5630f48d2bc6db21b26e63dfe/pcdet/models/backbones_3d/spconv_backbone.py#L593
I wonder why do the training and testing logic have to be different.

**Comment by hailanyi** [comment]
The  sequential processing for multiple transformed points is time-consuming. So I combined the tensors to a single tensor for parallel processing, that can slightly speed up the inference.
