### ISSUE TITLE
工程释放的TED_S基础模型的训练方式

### ISSUE THREAD

**Issue by ketherr** [hailanyi/TED#25]
作者您好，Readme有提到释放的基础模型如果要在kitti测试集上取得较好效果需要继续finetune，请问释放的基础模型只用了kitti数据集训练吗，与默认的TED-S config相比，有做过什么改动，谢谢，打扰

**Comment by ketherr** [comment]
主要是发现用3712 samples kitti训练集复现的模型与作者释放的TED-S模型效果有差异，想了解一下作者是否有采用过其它数据集的预训练模型等改动，谢谢

**Comment by hailanyi** [comment]
该模型没有在其他数据集上预训练过，这个开放的模型是我过去调优过程中精度最高的一个。如果和我开源的模型精度差异大于0.5%，那可能是运行环境的问题。我之前遇到过spconv版本问题，精度差异达到了3%。

**Comment by ketherr** [comment]
> 该模型没有在其他数据集上预训练过，这个开放的模型是我过去调优过程中精度最高的一个。如果和我开源的模型精度差异大于0.5%，那可能是运行环境的问题。我之前遇到过spconv版本问题，精度差异达到了3%。
     感谢回复，在Readme中有提到两种环境：ubuntu18.04+py3.6.9+torch1.8.1+spconv1.2.1+cu111+v100x8 以及 ubuntu18.04+py3.9.3+toch1.8.1+spconv2.1.22+cu111+2x3090，方便告知训练是哪一种吗，是不是作者释放的ted-s config即过去调优过程中最佳超参，谢谢
