### ISSUE TITLE
hi, I have some questions about TED

### ISSUE THREAD

**Issue by Ultra11nstinct** [hailanyi/TED#3]
Hi,@hailanyi 
Thanks for your contribution and the great work, I have two questions.
1)  It's really hard to download huge data from Google drive in China. Do you have a plan to upload the preprocessed data in other netdisk like Baidu netdist or Ali netdisk?

2)  I only have a 2080ti gpu with 10GB usable, I don know whether I can train it.  Is the GPU memory showed in Model Zoo a 1 batch?

Happy new year and looking forward to your reply. :)

**Comment by hailanyi** [comment]
1.  I will also upload the data on Baidu disk in future. Currently, you can generate the data by yourself using the provided [codes](https://github.com/hailanyi/TED/blob/master/tools/PENet/main.py)  and PENet model.
```
cd tools/PENet
python3 main.py --detpath [your path like: ../../data/kitti/training]
```
2.  The TED-S can be trained on GPU with 10GB memory (2 batch), but you need modify the proposal number in [config](https://github.com/hailanyi/TED/blob/master/tools/cfgs/models/kitti/TED-S.yaml) from 160 to 120 like:
```
225        TARGET_CONFIG:
226           BOX_CODER: ResidualCoder
227           ROI_PER_IMAGE: 120  # 160-> 120
```
The provided models in Model Zoo are trained with 2 batch. Using 1 batch may result in reduced 3D AP.

**Comment by Ultra11nstinct** [comment]
Got it.
Thank you very much @hailanyi
