### ISSUE TITLE
Distance Aware Data Aug

### ISSUE THREAD

**Issue by Soodep** [hailanyi/TED#31]
"During training, similar to GT-AUG (Shi, Wang, and Li 2019), we add the sampled points and bounding box into the training sample for
data augmentation." How did you do this, can you please provide an example for one frame.

**Comment by yanglanq** [comment]
I have found it at "pcdet/datasets/augmentor/database_sampler.py" called DADataBaseSampler, I think this works for the augmentation method they proposed.
