### ISSUE TITLE
The inference time of TED-M

### ISSUE THREAD

**Issue by Feidashen1** [hailanyi/TED#34]
Hello author，I had a problem replicating your code.
In the paper, the inference speed of TED-M is superior to SFD, but in my reproduction experiment, TEM-M performs worse than SFD, even worse (SFD is 0.13s per frame, TEM-M is 2.01s per frame). 
What is the possible reason? thanks!

**Comment by hailanyi** [comment]
To ensure better and stable performance, the released code is somewhat different from paper. The released code is based on multi-stage refinement, which require three RCNN detection heads. While the paper uses only single RCNN head for refinement. So the speed of this code is lower than paper but the accuracy is better than paper.

**Comment by Feidashen1** [comment]
> To ensure better and stable performance, the released code is somewhat different from paper. The released code is based on multi-stage refinement, which require three RCNN detection heads. While the paper uses only single RCNN head for refinement. So the speed of this code is lower than paper but the accuracy is better than paper.

Thank you for your reply! Can you provide a code or modification method for the RCNN detection head？Because I need to compare it with TED-M in my comparative experiment and measure its accuracy and inference time simultaneously. If I use the released code you provided now, it may not be very accurate.
