### ISSUE TITLE
Set Sync_bn == True后性能更差了

### ISSUE THREAD

**Issue by csjxchen** [hailanyi/TED#39]
我一开始用了dist_train时候，设置了一个train多类的配置文件，没有复现出论文结果，后来我注意那个sync_bn默认是False，我设置为True重新训练后，结果更是差得像是跑错了一样，sync_bn影响这么大的嘛，(batch_size_pergpu==2, rtx4090 x 4)
Car AP@0.70, 0.70, 0.70:
bbox AP:81.5334, 72.0265, 54.3557
bev  AP:80.3433, 62.9135, 53.9542
3d   AP:79.4474, 62.2500, 53.4173
aos  AP:73.62, 64.44, 49.18
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:82.1130, 69.5181, 57.1575
bev  AP:78.9817, 66.3993, 56.6061
3d   AP:78.1806, 63.1689, 53.5205
aos  AP:73.57, 61.58, 50.86
Car AP@0.70, 0.50, 0.50:
bbox AP:81.5334, 72.0265, 54.3557
bev  AP:81.5277, 72.1129, 63.1280
3d   AP:81.5240, 72.0833, 63.1023
aos  AP:73.62, 64.44, 49.18
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:82.1130, 69.5181, 57.1575
bev  AP:82.1346, 69.5302, 59.5978
3d   AP:82.1239, 69.5171, 59.5820
aos  AP:73.57, 61.58, 50.86
Pedestrian AP@0.50, 0.50, 0.50:
bbox AP:72.9022, 66.1238, 58.4425
bev  AP:57.5996, 51.4981, 45.0078
3d   AP:51.1632, 44.8705, 42.4977
aos  AP:55.38, 50.21, 44.26
Pedestrian AP_R40@0.50, 0.50, 0.50:
bbox AP:71.9307, 67.1668, 60.5231
bev  AP:55.1899, 49.7216, 43.5731
3d   AP:50.3886, 44.6111, 39.9284
aos  AP:52.64, 48.58, 43.49
Pedestrian AP@0.50, 0.25, 0.25:
bbox AP:72.9022, 66.1238, 58.4425
bev  AP:73.6792, 72.2074, 64.7820
3d   AP:73.6668, 72.1938, 64.6997
aos  AP:55.38, 50.21, 44.26
Pedestrian AP_R40@0.50, 0.25, 0.25:
bbox AP:71.9307, 67.1668, 60.5231
bev  AP:75.4670, 70.9054, 64.2100
3d   AP:75.4539, 70.8943, 64.1525
aos  AP:52.64, 48.58, 43.49
Cyclist AP@0.50, 0.50, 0.50:
bbox AP:79.8341, 69.2576, 61.3650
bev  AP:77.5997, 64.6157, 57.7342
3d   AP:76.9519, 57.5823, 57.0640
aos  AP:72.33, 60.86, 54.70
Cyclist AP_R40@0.50, 0.50, 0.50:
bbox AP:84.7664, 66.9035, 62.2235
bev  AP:82.1098, 62.4136, 58.1084
3d   AP:81.2366, 59.7446, 55.4550
aos  AP:75.65, 58.51, 54.53
Cyclist AP@0.50, 0.25, 0.25:
bbox AP:79.8341, 69.2576, 61.3650
bev  AP:78.6522, 65.4810, 58.6798
3d   AP:78.6522, 65.4810, 58.6798
aos  AP:72.33, 60.86, 54.70
Cyclist AP_R40@0.50, 0.25, 0.25:
bbox AP:84.7664, 66.9035, 62.2235
bev  AP:83.3066, 63.5213, 59.0797
3d   AP:83.3066, 63.5213, 59.0797
aos  AP:75.65, 58.51, 54.53

**Comment by csjxchen** [comment]
@hailanyi 烦劳作者给个答疑，任务实在有些紧

**Comment by lixingsky** [comment]
> [@hailanyi](https://github.com/hailanyi) 烦劳作者给个答疑，任务实在有些紧

我也遇到了这个问题，你解决了嘛，求助
