### ISSUE TITLE
Detect object in a customized KITTI dataset lidar scan

### ISSUE THREAD

**Issue by Mi97ch** [hailanyi/TED#8]
Hi, I need to run the object detector on a modified Lidar scan, is it possible to do that with this project?
I need as output the list of objects detected with their bounding boxes.

Thanks in advance for the help

**Comment by hailanyi** [comment]
Yes, please ensure your point cloud format is similar to KITTI and provide a dataset class similar to the (KittiDataset)[https://github.com/hailanyi/TED/blob/master/pcdet/datasets/kitti/kitti_dataset.py]. Then you can detect objects directly using our released model.
