### ISSUE TITLE
How to draw graph in tensorboard?

### ISSUE THREAD

**Issue by Bibena374** [hailanyi/TED#9]
I want to visualize a graph in tensorboard

and i add the code in /tools/train_utils/train_utils.py (line 67.)

![image](https://user-images.githubusercontent.com/89241103/214503808-bb86c1b8-0fc2-4962-be8e-7a197f3f1814.png)

but don't work and i received that...
![image](https://user-images.githubusercontent.com/89241103/214504186-2300b69b-5ef6-48d3-9741-5d6b3059653d.png)

how do i change the code?

Thank you in advance.

**Comment by hailanyi** [comment]
Sry, I have no idea as I did not use tensorboard to visualize the graph. But from the error, seems the ndarray is not supported for visualization.
